### PR TITLE
Update wheel gestures plugin docs page

### PR DESCRIPTION
**Pull request by xiel**
- updates the contents for the wheel gestures plugin page with usage info

Thanks for including it. 🙏

### CODE REVIEW

**Comment by davidcetinkaya** [comment]
Thank you for this Felix 🚀. Out of curiosity: Do you provide an UMD bundle with the Wheel Gestures package? 

Best,
David

**Comment by xiel** [comment]
Awesome, thanks @davidcetinkaya !

Currently there is no UMD bundle available, but I'll check how easy it is to make it available.

**Comment by davidcetinkaya** [comment]
@xiel the UMD bundle is not a requirement so don’t sweat it if you have other important things to do 😃. I would say that it’s more nice to have.

Cheers!
David

**Comment by xiel** [comment]
Was pretty easy to do, I sent you another very small PR. Makes it easier for users in the UMD world to use them all if needed.

**Comment by davidcetinkaya** [comment]
@xiel just an idea: If you don’t want to update the Wheel Gestures documentation in two places in the future (it can be tedious), you can just add a link to the Embla Carousel docs page for the plugin in your Readme. 

Thanks for your efforts 🚀!

Best,
David

**Comment by davidcetinkaya** [comment]
@xiel I also forgot to mention that I want to add a link to the GitHub repository and the plugin author on each plugin page.

**Comment by xiel** [comment]
Sounds good 👏

**Comment by davidcetinkaya** [comment]
[This feature](https://github.com/davidcetinkaya/embla-carousel/pull/243#issuecomment-983407266) will be added in:
- #255

**Pull request merged**
