### PR TITLE
Break the dragging animation if the slide index is equal to 0 or {max}

### PR DESCRIPTION
**Pull request by AdiMarianMutu**
I need this feature in the project I'm currently working on and I'm a little bit surprised that this super carousel does not have this feature out of the box.

Please check the [README.md](https://github.com/AdiMarianMutu/embla-carousel/blob/feature/drag-break-at-first-last-index/README.md) file for more info and a preview.

### CODE REVIEW

**Comment by nikrowell** [comment]
Hi @AdiMarianMutu 👋

Thanks for your work on this. One of Embla's primary goals is to be lightweight and extensible and it looks like your feature request is something that may already be possible with the existing API. 

What if you listened to the [select](https://www.embla-carousel.com/api/events/#select) event and then called [reInit()](https://www.embla-carousel.com/api/methods/#reinit) with `draggable: false` after reaching the last slide? Does that sound like it would work for your project's needs?

Hope that helps!

**Comment by AdiMarianMutu** [comment]
> Hi @AdiMarianMutu 👋
> 
> Thanks for your work on this. One of Embla's primary goals is to be lightweight and extensible and it looks like your feature request is something that may already be possible with the existing API.
> 
> What if you listened to the [select](https://www.embla-carousel.com/api/events/#select) event and then called [reInit()](https://www.embla-carousel.com/api/methods/#reinit) with `draggable: false` after reaching the last slide? Does that sound like it would work for your project's needs?
> 
> Hope that helps!

Hi @nikrowell.

Thanks for the feedback. I have already tried to do it with the API, but because of the `transform: translate3d` injected style, there is always a small gap before breaking the dragging.

That's why the condition must exists **before** injecting the style.

Please check the preview inside the [README.md](https://github.com/AdiMarianMutu/embla-carousel/tree/feature/drag-break-at-first-last-index#readme)

**Comment by davidcetinkaya** [comment]
Hello @AdiMarianMutu,

Thank you for your contribution. This is related to issue #42. You can use the undocumented feature `embla.dangerouslyGetEngine()` to achieve what you want. This method exposes the internal functionality of Embla and can be used to extend Embla to cover most of the use cases for carousels. 

Something along these lines should work:
```js
const preventEdgeScrolling = (embla) => {
  const { limit, target, location, scrollTo } = embla.dangerouslyGetEngine();

  return () => {
    if (limit.reachedMax(target.get())) {
      if (limit.reachedMax(location.get())) location.set(limit.max);
      target.set(limit.max);
      scrollTo.distance(0, false);
    }
    if (limit.reachedMin(target.get())) {
      if (limit.reachedMin(location.get())) location.set(limit.min);
      target.set(limit.min);
      scrollTo.distance(0, false);
    }
  };
};

embla.on("scroll", preventEdgeScrolling(embla));
```

I hope this helps.

Best,
David

**Comment by AdiMarianMutu** [comment]
Hi @davidcetinkaya,

Thanks for the solution, it's working perfectly!

I'm really sorry about this "abusive" pull request, I've completely missed [this](https://github.com/davidcetinkaya/embla-carousel/issues/187#issue-873669552) guide line.

However, I'm unable to find the documentation about `dangerouslyGetEngine()` in the official [methods doc](https://www.embla-carousel.com/api/methods/), this would have been really useful if it was present.

**Comment by davidcetinkaya** [comment]
Hi @AdiMarianMutu,

Not a problem. As I mentioned in my [comment](https://github.com/davidcetinkaya/embla-carousel/pull/206#issuecomment-895842283) `dangerouslyGetEngine()` not being documented is intentional. When I created the method, it was intended to aid plugin authors with maximum extensibility. Another purpose was that it enabled for extending the carousel with features that either wouldn't be added to the core itself, or features that would be released later on. But I didn't want people creating a lot of issues about it because you really have to know what you're doing when using it, and that's why I kept it undocumented.

Cheers,
David

**Comment by AdiMarianMutu** [comment]
> Hi @AdiMarianMutu,
> 
> Not a problem. As I mentioned in my [comment](https://github.com/davidcetinkaya/embla-carousel/pull/206#issuecomment-895842283) `dangerouslyGetEngine()` not being documented is intentional. When I created the method, it was intended to aid plugin authors with maximum extensibility. Another purpose was that it enabled for extending the carousel with features that either wouldn't be added to the core itself, or features that would be released later on. But I didn't want people creating a lot of issues about it because you really have to know what you're doing when using it, and that's why I kept it undocumented.
> 
> Cheers,
> David

**Pull request closed without merging**
