### PR TITLE
Trigger Badge Refresh

### PR DESCRIPTION
**Pull request by muizzk**

### CODE REVIEW

**Comment by davidcetinkaya** [comment]
Hi @muizzk ,
Did you remove the automatic NPM publishing job for testing purposes?

**Comment by muizzk** [comment]
@davidcetinkaya yes, that's correct. Feel free to ignore this PR as the badge issue wasn't fixed as I had expected. Thanks

**Comment by davidcetinkaya** [comment]
@muizzk Thanks for letting me know. I'm going to tweak the **travis.yml** config and see if I can solve the badge issue that way.

**Comment by muizzk** [comment]
Hey @davidcetinkaya , tweaking the config will not change the badge by itself. I was checking out a setting on your profile and needed to trigger a new build to see if the badge would refresh. I'll provide more details on the ticket. Cheers

**Comment by davidcetinkaya** [comment]
Hi @muizzk ,
Actually, changing to [this config](https://github.com/davidcetinkaya/embla-carousel/blob/master/.travis.yml) made it work. And here's [the diff](https://github.com/davidcetinkaya/embla-carousel/commit/2b043c8bbf226acf838c7918d91cf49cd8d37c1f).

**Comment by muizzk** [comment]
Glad my colleague was able to help. Cheers

**Comment by davidcetinkaya** [comment]
Thanks for the help!

**Pull request closed without merging**
